name: iqra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  quran: ^1.3.1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  flutter_compass_v2: ^1.0.3
  auto_size_text: ^3.0.0
  just_audio: ^0.9.33
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  image_dark: assets/splashDark.png
  color_dark: "#121F24"
  android_12:
    image: assets/splash12Defualt.png
    icon_background_color: "#FFFFFF"
    color: "#FFFFFF"
    image_dark: assets/Splash12Dark.png
    color_dark: "#121F24"
    icon_background_color_dark: "#121F24"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png
  adaptive_icon_background: "#FFFFFF"
  cupertino_icons: ^1.0.6

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/
     - assets/database/

